#!/usr/bin/env ruby


# ENV['RAILS_ENV'] ||= 'development'
# require File.dirname(__FILE__) + '/../config/environment'
require 'digest/md5'
require 'csv'
require 'ftools'
require 'mediawiki-gateway/lib/media_wiki'


RAILS_ROOT = File.dirname(__FILE__)
 

class Page
  attr_accessor :name, :folder, :content, :last_update, :author_name  
end
class User
	attr_accessor :name, :realname, :custom1, :custom2
end

@users = []
mw = MediaWiki::Gateway.new('http://www.wikem.org/w/api.php')
mw.login('Robot2','wikem-vona')
# mw.create('PageTitle', 'Hello world!', 'Comment: My first page')

#mw.create( 'User:Ckim', 'Hello world','Comment: My first page')
#puts "page made?"
 
allusers = mw.list_all_users()
counter = 0
length = allusers.length
iterations = length / 4

counter.upto(iterations-1) do
	u = User.new
	u.name = allusers[counter]
	u.realname = allusers[counter+1]
	u.custom1 = allusers[counter+2]
	u.custom2 = allusers[counter+3]
	counter+=4
	@users << u
end

#userstring = 'User:'
puts "creating pages"
@users.each do |x|
	#puts "username is #{x.name}"
	#puts "realname is #{x.realname} #{x.custom1}"
	#puts "from #{x.custom2}"
	temp = "User:" + x.name
	content = x.realname + " " + x.custom1 + "." +  "\n\n " + x.custom2 + "."
	temppage = mw.get(temp)
	#if page is nil then write the page
	if (temppage == nil)
		puts mw.create(temp, content, {:overwrite => true, :summary => 'autogenerated page'})
	else
		puts "no page created for #{x.name}"
		end
end
#puts mw.create(config.article, content, {:overwrite => true, :summary => config.summary})




